name: CI-python-test
on:
  push:
    branches:
      ["main"]
  pull_request:
    branches:
      ["main"]
jobs:
  test:
    runs-on: ubutntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Setup python
      uses: actions/setup-python@v5

    - name: Install dependieces
      run: | 
        pip install --upgrade 
        pip install -r requirements.txt

    - name: Lint (ruff)
      run: ruff check .
    

    